# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.6.1/www/docs/static/schema-pro.json
version: 1

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: gophpfetch
    buildmode: c-shared
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums_darwin.txt"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format: binary
    files:
      - checksums_darwin.txt
      - none*
    builds_info:
      group: root
      owner: root